CREATE TABLE f (
	id INT PRIMARY KEY
);
CREATE TABLE e (
	id INT PRIMARY KEY,
	f_id INT REFERENCES f
);
CREATE TABLE d (
	id INT PRIMARY KEY
);
CREATE TABLE c (
	id INT PRIMARY KEY
);
CREATE TABLE b (
	id INT PRIMARY KEY,
	d_id INT REFERENCES d,
	e_id INT REFERENCES e
);
CREATE TABLE a (
	id INT PRIMARY KEY,
	b_id INT REFERENCES b,
	c_id INT REFERENCES c
);

